package acquistosistema;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ScaricareMaterialeAcquistatoTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void testScaricaMaterialePresente() {
		driver.get("http://localhost:8080/SocialNotes/homepage.jsp");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.linkText("Storico acquisti")).click();
		driver.findElement(By.linkText("Storico acquisti")).click();
		driver.findElement(By.id("inlineCheckbox1")).click();
		driver.findElement(By.cssSelector(".candidates-list:nth-child(2) #inlineCheckbox1")).click();
		driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
	}
	@Test
	public void testScaricaMaterialeNonPresente() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 1053));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.linkText("Storico acquisti")).click();
		driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
		assertFalse(driver.findElement(By.id("inlineCheckbox1")).isSelected());
		assertFalse(driver.findElement(By.cssSelector(".candidates-list:nth-child(2) #inlineCheckbox1")).isSelected());
		assertFalse(driver.findElement(By.cssSelector(".candidates-list:nth-child(3) #inlineCheckbox1")).isSelected());
	}
}
