package acquistosistema;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;
public class VisualizzazioneStoricoAcquistiTest {
	private WebDriver driver;
	JavascriptExecutor js;
	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver.exe");
		//System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver");
		driver = new ChromeDriver(new ChromeOptions().addArguments("--remote-allow-origins=*"));
		js = (JavascriptExecutor) driver;
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void testVisualizzazioneStoricoAcquistiNonPresenti() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("nik");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Barella123");
		driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.linkText("Storico acquisti")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".card"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testVisualizzazioneStoricoAcquistiPresenti() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.linkText("Storico acquisti")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".container:nth-child(1)"));
			assert(elements.size() > 0);
		}
	}
}
