// Generated by Selenium IDE
package newssistema;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;
public class CaricamentoNewsTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver.exe");
    //System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver");
    driver = new ChromeDriver(new ChromeOptions().addArguments("--remote-allow-origins=*"));
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  private boolean isAttributePresent(WebElement element, String attribute) {
  Boolean result = false;
  try {
  	String value = element.getAttribute(attribute);
  	if (value != null){
  		result = true;
  	}
  } catch (Exception e) {}
 	return result;
  }
  
  @Test
  public void testCaricamentoNewsEffettuato() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("NewsManager");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("News1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("picture")).sendKeys("C:\\fakepath\\graffe-di-carnevale.jpg");
    driver.findElement(By.name("titolo")).click();
    driver.findElement(By.name("titolo")).sendKeys("nuova news");
    driver.findElement(By.name("argomento")).click();
    driver.findElement(By.name("argomento")).sendKeys("news");
    driver.findElement(By.name("contenuto")).click();
    driver.findElement(By.name("contenuto")).sendKeys("prova news");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testCaricamentoNewsArgomentoNonInserito() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("NewsManager");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("News1");
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("picture")).sendKeys("C:\\fakepath\\graffe-di-carnevale.jpg");
    driver.findElement(By.name("titolo")).click();
    driver.findElement(By.name("titolo")).sendKeys("titolo news");
    driver.findElement(By.cssSelector(".btn")).click();
    assertEquals(isAttributePresent(driver.findElement(By.id("argomento")),"required"),true);
  }
  @Test
  public void testCaricamentoNewsContenutoNonInserito() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("NewsManager");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("News1");
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("picture")).sendKeys("C:\\fakepath\\graffe-di-carnevale.jpg");
    driver.findElement(By.name("titolo")).click();
    driver.findElement(By.name("titolo")).sendKeys("titolo news");
    driver.findElement(By.name("argomento")).click();
    driver.findElement(By.name("argomento")).sendKeys("argomento news");
    driver.findElement(By.cssSelector(".btn")).click();
    assertEquals(isAttributePresent(driver.findElement(By.id("contenuto")),"required"),true);
  }
  @Test
  public void testCaricamentoNewsImmagineNonInserita() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("NewsManager");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("News1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    assertEquals(isAttributePresent(driver.findElement(By.id("picture")),"required"),true);
  }
  @Test
  public void testCaricamentoNewsTipoFileNonValido() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("NewsManager");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("News1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("picture")).sendKeys("C:\\fakepath\\file.dat");
    assertThat(driver.switchTo().alert().getText(), is("Tipo del file non valido"));
  }
  @Test
  public void testCaricamentoNewsTitoloNonInserito() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("NewsManager");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("News1");
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("picture")).sendKeys("C:\\fakepath\\graffe-di-carnevale.jpg");
    driver.findElement(By.cssSelector(".btn")).click();
    assertEquals(isAttributePresent(driver.findElement(By.id("titolo")),"required"),true);
  }
}
