// Generated by Selenium IDE
package materialesistema;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
public class AggiungereFeedbackTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver.exe");
    //System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver");
    driver = new ChromeDriver(new ChromeOptions().addArguments("--remote-allow-origins=*"));
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  private boolean isAttributePresent(WebElement element, String attribute) {
  Boolean result = false;
  try {
  	String value = element.getAttribute(attribute);
  	if (value != null){
  		result = true;
  	}
  } catch (Exception e) {}
 	return result;
  }
  
  @Test
  public void testAggiungereFeedbackConValutazione() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("fry");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("Despacit0");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".card:nth-child(9) .card-title")).click();
    driver.findElement(By.id("exampleFormControlTextarea1")).click();
    driver.findElement(By.id("exampleFormControlTextarea1")).sendKeys("ottimi appunti");
    driver.findElement(By.cssSelector("#stella > label:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".btn-primary:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector(".card:nth-child(2) p")).getText(), is("ottimi appunti"));
  }
  @Test
  public void testAggiungereFeedbackNonValido() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("fry");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("Despacit0");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".card:nth-child(6) .card-title")).click();
    driver.findElement(By.cssSelector("label:nth-child(8)")).click();
    driver.findElement(By.cssSelector(".btn-primary:nth-child(2)")).click();
    
    assertEquals(isAttributePresent(driver.findElement(By.id("exampleFormControlTextarea1")),"required"),true);
  }
  @Test
  public void testAggiungereFeedbackSenzaValutazione() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("fry");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("Despacit0");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".card:nth-child(6) .card-title")).click();
    driver.findElement(By.id("exampleFormControlTextarea1")).click();
    driver.findElement(By.id("exampleFormControlTextarea1")).sendKeys("appunti inutili");
    driver.findElement(By.cssSelector(".btn-primary:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("appunti inutili"));
  }
}
