// Generated by Selenium IDE
package materialesistema;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CaricaMaterialeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver");
	//System.setProperty("webdriver.chrome.driver","test/profilosistema/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  private boolean isAttributePresent(WebElement element, String attribute) {
  Boolean result = false;
  try {
  String value = element.getAttribute(attribute);
  if (value != null){
  result = true;
  }
  } catch (Exception e) {}
  return result;
  }
  
  @Test
  public void testCaricamentoMaterialeEffettuato() {
    driver.get("http://localhost:8080/SocialNotes/homepage.jsp");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("fry");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("Despacit0");
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("formFile")).click();
    driver.findElement(By.id("formFile")).sendKeys("C:\\fakepath\\Laboratorio-esempio0.pdf");
    driver.findElement(By.name("Anteprima")).click();
    driver.findElement(By.name("Anteprima")).sendKeys("C:\\fakepath\\pngtree-a-pile-of-books-png-image_3271610.png");
    driver.findElement(By.name("Descrizione")).click();
    driver.findElement(By.name("Descrizione")).sendKeys("prova laboratorio Mobile programming");
    driver.findElement(By.name("Corso")).click();
    driver.findElement(By.name("Corso")).sendKeys("MP");
    driver.findElement(By.cssSelector(".bottone-principale")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testCaricamentoMaterialeDescrizioneNonPresente() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("fry");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("Despacit0");
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("formFile")).click();
    driver.findElement(By.id("formFile")).sendKeys("C:\\fakepath\\Laboratorio-esempio0.pdf");
    driver.findElement(By.name("Anteprima")).click();
    driver.findElement(By.name("Anteprima")).sendKeys("C:\\fakepath\\pngtree-a-pile-of-books-png-image_3271610.png");
    driver.findElement(By.cssSelector(".bottone-principale")).click();
    assertEquals(isAttributePresent(driver.findElement(By.id("descrizione")),"required"),true);
  }
  @Test
  public void testCaricamentoMaterialeFileDimensioneEccessiva() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("fry");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("Despacit0");
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("formFile")).click();
    driver.findElement(By.id("formFile")).sendKeys("C:\\fakepath\\reti di calcolatori e internet - top down.pdf");
    assertThat(driver.switchTo().alert().getText(), is("Dimensione file eccessiva, seleziona un file che sia grande al massimo 50MB"));
  }
  @Test
  public void testCaricamentoMaterialeFileNonInserito() {
    driver.get("http://localhost:8080/SocialNotes/homepage.jsp");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("fry");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("Despacit0");
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".bottone-principale")).click();
    assertEquals(isAttributePresent(driver.findElement(By.id("formFile")),"required"),true);
  }
  @Test
  public void testCaricamentoMaterialeFileNonValido() {
    driver.get("http://localhost:8080/SocialNotes/homepage.jsp");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("fry");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("Despacit0");
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("formFile")).click();
    driver.findElement(By.id("formFile")).sendKeys("‪C:\\fakepath\\file.dat");
    assertThat(driver.switchTo().alert().getText(), is("Tipo del file non valido"));
  }
}
