// Generated by Selenium IDE
package profilosistema;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class LoginTest {
  private WebDriver driver;

  JavascriptExecutor js;
  @Before
  public void setUp() {
    //System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver");
    System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver.exe");
    driver = new ChromeDriver(new ChromeOptions().addArguments("--remote-allow-origins=*"));
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testLoginEffettuato() throws InterruptedException {
    System.out.println("ciao");
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("fry");
    driver.findElement(By.id("inputPassword")).sendKeys("Despacit0");
    driver.findElement(By.cssSelector(".btn")).click();
    Thread.sleep(5000);
    assertThat(driver.getTitle(), is("SocialNotes - Home"));
    driver.close();
  }

  //CR2
  @Test
  public void testLoginMailNoVerificata(){
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1382, 736));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("rocco0");
    driver.findElement(By.id("inputPassword")).sendKeys("saddaSapeFa0");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector("small")).getText(), is("Mail non verificata"));
    driver.close();
  }
  @Test
  public void testLoginPasswordNonValida() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("fry");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("despacito");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector("small")).getText(), is("Accesso negato"));
  }
  @Test
  public void testLoginUsernameNonPresente() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("pluto");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("paperino");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }

  @Test
  public void testLoginUtenteBloccato(){
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("Fabio");
    driver.findElement(By.id("inputPassword")).click();
    driver.findElement(By.id("inputPassword")).sendKeys("Cannavaro0");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector("small")).getText(), is("Sei attualmente bloccato"));

  }
  @Test
  public void testLoginLimitiTentativi() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    for (int i = 0; i<5; i++){
      driver.findElement(By.id("inputEmail")).click();
      driver.findElement(By.id("inputEmail")).sendKeys("VanDack1");
      driver.findElement(By.id("inputPassword")).click();
      driver.findElement(By.id("inputPassword")).sendKeys("Cannavaro0");
      driver.findElement(By.cssSelector(".btn")).click();
    }
    assertThat(driver.findElement(By.cssSelector("small")).getText(), is("Accesso negato, eccessivo numero di tentativi falliti. Riprova tra 5 minuti"));
  }
}
