// Generated by Selenium IDE
package profilosistema;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RecuperoPasswordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver");
	//System.setProperty("webdriver.chrome.driver","test/profilosistema/chromedriver.exe");
    driver = new ChromeDriver(new ChromeOptions().addArguments("--remote-allow-origins=*"));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testRecuperoPasswordPinNonCorretto() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.linkText("Hai dimenticato la password?")).click();
    driver.findElement(By.id("inputUser")).click();
    driver.findElement(By.id("inputUser")).sendKeys("fry");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("inputUser")).click();
    driver.findElement(By.id("inputUser")).sendKeys("fry");
    driver.findElement(By.id("inputPin")).click();
    driver.findElement(By.id("inputPin")).sendKeys("123");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void testRecuperoPasswordEffettuato() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.linkText("Hai dimenticato la password?")).click();
    driver.findElement(By.id("inputUser")).click();
    driver.findElement(By.id("inputUser")).sendKeys("fry");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("inputUser")).click();
    driver.findElement(By.id("inputUser")).sendKeys("fry");
    driver.findElement(By.id("inputPin")).click();
    driver.findElement(By.id("inputPin")).sendKeys("40452");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.getTitle(), is("Login"));
  }
  @Test
  public void testRecuperoPasswordUsernameNonPresente() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1181, 852));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.linkText("Hai dimenticato la password?")).click();
    driver.findElement(By.id("inputUser")).click();
    driver.findElement(By.id("inputUser")).sendKeys("pluto");
    driver.findElement(By.cssSelector(".btn")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
      assert(elements.size() > 0);
    }
  }

  @Test
  public void testRecuperoPasswordFormatoErrato() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1680, 964));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.linkText("Hai dimenticato la password?")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ggallocca1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ggallocca1");
    driver.findElement(By.id("inputPin")).click();
    try {
      Thread.sleep(15000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("password1")).click();
    driver.findElement(By.id("password1")).sendKeys("ciao");
    driver.findElement(By.id("password2")).sendKeys("Password1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Attenzione! Formato password errato\n×"));
  }

  @Test
  public void testRecuperoPasswordDiverse() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1680, 964));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.linkText("Hai dimenticato la password?")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ggallocca1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ggallocca1");
    driver.findElement(By.id("inputPin")).click();
    try {
      Thread.sleep(15000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("password1")).click();
    driver.findElement(By.id("password1")).sendKeys("Password1");
    driver.findElement(By.id("password2")).sendKeys("password1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Attenzione! Le password non coincidono\n×"));
  }

  @Test
  public void testRecuperoPasswordPinErrato() {
    driver.get("http://localhost:8080/SocialNotes/");
    driver.manage().window().setSize(new Dimension(1680, 964));
    driver.findElement(By.linkText("Accedi")).click();
    driver.findElement(By.linkText("Hai dimenticato la password?")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ggallocca1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("ggallocca1");
    driver.findElement(By.id("inputPin")).click();
    driver.findElement(By.id("inputPin")).sendKeys("1231312313131313");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Attenzione! Pin inserito errato\n×"));
  }
}
