package profilosistema;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RicercaUtentiTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver","test/materialesistema/chromedriver");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void testRicercaUtentiByUsernameNoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.id("navbarDropdown")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("calif");
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByUsernameRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.id("navbarDropdown")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("fry");
		driver.findElement(By.cssSelector("label:nth-child(10)")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaByCognomeVuotoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".form-signin")).click();
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.id("navbarDropdown")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.cssSelector("label:nth-child(2)")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByCognomeNoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".bi-person-lines-fill")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("Califano");
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByCognomeNotPresentNoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".bi-person-lines-fill > path")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("j");
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByCognomeNotPresentRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".bi-person-lines-fill")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("j");
		driver.findElement(By.cssSelector("label:nth-child(8)")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByCognomeRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".bi-person-lines-fill")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("Di lauro");
		driver.findElement(By.cssSelector("label:nth-child(10)")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByCognomeVuotoNoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".bi-person-lines-fill")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByNameNoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.id("navbarDropdown")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("alfonso");
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByNameNotPresentNoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.id("navbarDropdown")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("j");
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByNameNotPresentRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.id("navbarDropdown")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("j");
		driver.findElement(By.cssSelector("label:nth-child(6)")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByNameRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".bi-person-lines-fill")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("francesco");
		driver.findElement(By.cssSelector("label:nth-child(6)")).click();
		driver.findElement(By.cssSelector("label:nth-child(10)")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByNameVuotoNoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.id("navbarDropdown")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByNameVuotoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.id("navbarDropdown")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.cssSelector("label:nth-child(2)")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByUsernameNotPresentNoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".bi-person-lines-fill")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("j");
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByUsernameNotPresentRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".bi-person-lines-fill > path")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.name("search")).click();
		driver.findElement(By.name("search")).sendKeys("j");
		driver.findElement(By.cssSelector("label:nth-child(4)")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".alert"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByUsernameVuotoNoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.id("navbarDropdown")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
	@Test
	public void testRicercaUtentiByUsernameVuotoRating() {
		driver.get("http://localhost:8080/SocialNotes/");
		driver.manage().window().setSize(new Dimension(1848, 913));
		driver.findElement(By.linkText("Accedi")).click();
		driver.findElement(By.id("inputEmail")).sendKeys("sime00");
		driver.findElement(By.cssSelector(".text-center")).click();
		driver.findElement(By.id("inputPassword")).click();
		driver.findElement(By.id("inputPassword")).sendKeys("Sime00");
		driver.findElement(By.cssSelector(".btn")).click();
		driver.findElement(By.cssSelector(".bi-person-lines-fill")).click();
		driver.findElement(By.linkText("Cerca persone")).click();
		driver.findElement(By.cssSelector("label:nth-child(4)")).click();
		driver.findElement(By.cssSelector(".btn-default:nth-child(2)")).click();
		{
			List<WebElement> elements = driver.findElements(By.cssSelector(".table-responsive"));
			assert(elements.size() > 0);
		}
	}
}
